
version: "3"

services:
  tomcat:
    image: paulnguyen/gumball-tomcat:7.0.92
    deploy:
      replicas: 2
    volumes:
      - /tmp:/tmp
    networks:
      - network   
    ports:
      - 8080-8081:8080    
    restart: always
    depends_on:
      - mysql      
  mysql:
    image: mysql:5.5
    networks:
      - network    
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=cmpe281   

volumes:
  schemas:
    external: false

networks:
  network:
    driver: bridge
