
version: "3"

services:
  gumball:
    image: gumball
    networks:
      - gumball   
    ports:
      - 8080-8081:8080    
    restart: always
    depends_on:
      - mysql      
  mysql:
    image: mysql:5.5
    networks:
      - gumball    
    ports:
      - 3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=cmpe281   

volumes:
  schemas:
    external: false

networks:
  gumball:
    driver: bridge
