
version: "3"

services:
  gumball:
    image: gumball
    networks:
      - gumball   
    ports:
      - 8080    
    restart: always
    depends_on:
      - mysql      
  lb:
    image: dockercloud/haproxy
    # https://hub.docker.com/r/dockercloud/haproxy/
    # options: roundrobin (default), static-rr, source, leastconn
    # see: https://cbonte.github.io/haproxy-dconv/configuration-1.5.html#4-balance
    environment:
      - BALANCE=leastconn
    depends_on:
      - gumball
    networks:
      - gumball     
    links:
     - gumball
    ports:
     - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mysql:
    image: mysql:5.5
    networks:
      - gumball    
    ports:
      - 3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=cmpe281   

volumes:
  schemas:
    external: false

networks:
  gumball:
    driver: bridge
